theme: jekyll-theme-architect
title: [VERB Replication Package]
description: [the replication package for API Method Recommendation via Explicit Matching of Functionality Verb Phrases
]
show_downloads: true
is_user_page: true
github.is_user_page: true